package com.maua.roubit.shared.domain.enums;

public enum CoursesEnum {
    ADMINISTRACAO,
    ARQUITETURA_E_URBANISMO,
    CIENCIA_DA_COMPUTACAO,
    DESIGN,
    ENGENHARIA_CIVIL,
    ENGENHARIA_DE_ALIMENTOS,
    ENGENHARIA_DE_COMPUTACAO,
    ENGENHARIA_DE_CONTROLE_E_AUTOMACAO,
    ENGENHARIA_DE_PRODUCAO,
    ENGENHARIA_ELETRICA,
    ENGENHARIA_ELETRONICA,
    ENGENHARIA_MECANICA,
    ENGENHARIA_QUIMICA,
    INTELIGENCIA_ARTIFICIAL_E_CIENCIAS_DE_DADOS,
    RELACOES_INTERNACIONAIS,
    SISTEMAS_DE_INFORMACAO
}
