name: CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Set environment variables
      run: echo "APPLICATION_NAME=${{ secrets.APPLICATION_NAME }}" >> $GITHUB_ENV
    - name: Build and test with Maven
      run: mvn -B verify --file pom.xml
      env:
        APPLICATION_NAME: ${{ secrets.APPLICATION_NAME }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
        DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
        JPA_DDL: ${{ secrets.JPA_DDL }}
        JPA_SHOW_SQL: ${{ secrets.JPA_SHOW_SQL }}
        JPA_OPEN_IN_VIEW: ${{ secrets.JPA_OPEN_IN_VIEW }}
    - name: Upload coverage results
      if: success() && steps.test.outputs.coverage_report != ''
      uses: codecov/codecov-action@v3
      with:
        file: path/to/coverage-report.xml
 
